/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package melate;

/**
 *
 * @author Mao
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUno = new javax.swing.JTextField();
        txtDos = new javax.swing.JTextField();
        txtCuatro = new javax.swing.JTextField();
        txtTres = new javax.swing.JTextField();
        txtSeis = new javax.swing.JTextField();
        txtCinco = new javax.swing.JTextField();
        txtAdicional = new javax.swing.JTextField();
        btnSuerte = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        resultadoBoleto1 = new javax.swing.JLabel();
        resultadoBoleto2 = new javax.swing.JLabel();
        resultadoBoleto3 = new javax.swing.JLabel();
        resultadoBoleto4 = new javax.swing.JLabel();
        resultadoBoleto5 = new javax.swing.JLabel();
        resultadoBoleto10 = new javax.swing.JLabel();
        resultadoBoleto9 = new javax.swing.JLabel();
        resultadoBoleto8 = new javax.swing.JLabel();
        resultadoBoleto7 = new javax.swing.JLabel();
        resultadoBoleto6 = new javax.swing.JLabel();
        resultadoBoleto12 = new javax.swing.JLabel();
        resultadoBoleto11 = new javax.swing.JLabel();
        resultadoBoleto14 = new javax.swing.JLabel();
        resultadoBoleto13 = new javax.swing.JLabel();
        resultadoBoleto15 = new javax.swing.JLabel();
        resultadoBoleto17 = new javax.swing.JLabel();
        resultadoBoleto16 = new javax.swing.JLabel();
        resultadoBoleto19 = new javax.swing.JLabel();
        resultadoBoleto18 = new javax.swing.JLabel();
        resultadoBoleto20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Numeros ganadores"));

        btnSuerte.setText("Suerte");
        btnSuerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuerteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTres, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuerte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSuerte))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mis Numeros"));

        jLabel1.setText("Boleto 1 52 54 18 6 41 34 ");

        jLabel2.setText("Boleto 2 2 17 51 40 41 16 ");

        jLabel3.setText("Boleto 3 54 32 4 19 7 8 ");

        jLabel4.setText("Boleto 4 43 56 28 18 20 11");

        jLabel5.setText("Boleto 5 15 18 40 38 45 55");

        jLabel6.setText("Boleto 6 12 40 36 46 44 13");

        jLabel7.setText("Boleto 7 32 44 13 10 18 31");

        jLabel8.setText("Boleto 8 8 33 30 31 47 43");

        jLabel9.setText("Boleto 9 14 27 12 39 41 35");

        jLabel10.setText("Boleto 10 46 49 35 43 6 48");

        jLabel11.setText("Boleto 11 45 7 36 30 22 19");

        jLabel12.setText("Boleto 12 20 39 29 10 22 19");

        jLabel13.setText("Boleto 13 53 8 47 30 12 13");

        jLabel14.setText("Boleto 14 17 13 2 5 27 6");

        jLabel15.setText("Boleto 15 24 39 13 20 22 10 ");

        jLabel16.setText("Boleto 16 41 7 33 38 3 13");

        jLabel17.setText("Boleto 17 19 38 37 25 51 2");

        jLabel18.setText("Boleto 18 54 47 34 35 42 51");

        jLabel19.setText("Boleto 19 1 43 46 31 25 24");

        jLabel20.setText("Boleto 20 56 28 31 54 30 46");

        resultadoBoleto1.setText("0");

        resultadoBoleto2.setText("0");

        resultadoBoleto3.setText("0");

        resultadoBoleto4.setText("0");

        resultadoBoleto5.setText("0");

        resultadoBoleto10.setText("0");

        resultadoBoleto9.setText("0");

        resultadoBoleto8.setText("0");

        resultadoBoleto7.setText("0");

        resultadoBoleto6.setText("0");

        resultadoBoleto12.setText("0");

        resultadoBoleto11.setText("0");

        resultadoBoleto14.setText("0");

        resultadoBoleto13.setText("0");

        resultadoBoleto15.setText("0");

        resultadoBoleto17.setText("0");

        resultadoBoleto16.setText("0");

        resultadoBoleto19.setText("0");

        resultadoBoleto18.setText("0");

        resultadoBoleto20.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(41, 41, 41)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(resultadoBoleto10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(resultadoBoleto9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultadoBoleto8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultadoBoleto7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultadoBoleto6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(resultadoBoleto15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(resultadoBoleto14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultadoBoleto13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultadoBoleto12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultadoBoleto11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(resultadoBoleto20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(resultadoBoleto19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultadoBoleto18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultadoBoleto17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultadoBoleto16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resultadoBoleto5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(41, 41, 41)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(resultadoBoleto4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(resultadoBoleto3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(resultadoBoleto2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(45, 45, 45)
                                        .addComponent(resultadoBoleto1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(resultadoBoleto1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(resultadoBoleto2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(resultadoBoleto3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(resultadoBoleto4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(resultadoBoleto5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(resultadoBoleto6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(resultadoBoleto7)
                                        .addGap(56, 56, 56))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(resultadoBoleto8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(resultadoBoleto9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoBoleto10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(resultadoBoleto11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoBoleto12)
                                .addGap(56, 56, 56))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(resultadoBoleto13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoBoleto14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultadoBoleto15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(resultadoBoleto16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoBoleto17)
                                .addGap(56, 56, 56))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(resultadoBoleto18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultadoBoleto19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultadoBoleto20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuerteActionPerformed
        boleto1();
        boleto2();
        boleto3();
        boleto4();
        boleto5();
        boleto6();
        boleto7();
        boleto8();
        boleto9();
        boleto10();
        boleto11();
        boleto12();
        boleto13();
        boleto14();
        boleto15();
        boleto16();
        boleto17();
        boleto18();
        boleto19();
        boleto20();
    }//GEN-LAST:event_btnSuerteActionPerformed
    // iniciamos los boletos
    private void boleto1(){
        int boleto1=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("52")) boleto1++;
        if (txtDos.getText().equals("52")) boleto1++;
        if (txtTres.getText().equals("52")) boleto1++;
        if (txtCuatro.getText().equals("52")) boleto1++;
        if (txtCinco.getText().equals("52")) boleto1++;
        if (txtSeis.getText().equals("52")) boleto1++;
        if (txtAdicional.getText().equals("52")) boleto1++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("54")) boleto1++;
        if (txtDos.getText().equals("54")) boleto1++;
        if (txtTres.getText().equals("54")) boleto1++;
        if (txtCuatro.getText().equals("54")) boleto1++;
        if (txtCinco.getText().equals("54")) boleto1++;
        if (txtSeis.getText().equals("54")) boleto1++;
        if (txtAdicional.getText().equals("54")) boleto1++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("18")) boleto1++;
        if (txtDos.getText().equals("18")) boleto1++;
        if (txtTres.getText().equals("18")) boleto1++;
        if (txtCuatro.getText().equals("18")) boleto1++;
        if (txtCinco.getText().equals("18")) boleto1++;
        if (txtSeis.getText().equals("18")) boleto1++;
        if (txtAdicional.getText().equals("18")) boleto1++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("6")) boleto1++;
        if (txtDos.getText().equals("6")) boleto1++;
        if (txtTres.getText().equals("6")) boleto1++;
        if (txtCuatro.getText().equals("6")) boleto1++;
        if (txtCinco.getText().equals("6")) boleto1++;
        if (txtSeis.getText().equals("6")) boleto1++;
        if (txtAdicional.getText().equals("6")) boleto1++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("41")) boleto1++;
        if (txtDos.getText().equals("41")) boleto1++;
        if (txtTres.getText().equals("41")) boleto1++;
        if (txtCuatro.getText().equals("41")) boleto1++;
        if (txtCinco.getText().equals("41")) boleto1++;
        if (txtSeis.getText().equals("41")) boleto1++;
        if (txtAdicional.getText().equals("41")) boleto1++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("34")) boleto1++;
        if (txtDos.getText().equals("34")) boleto1++;
        if (txtTres.getText().equals("34")) boleto1++;
        if (txtCuatro.getText().equals("34")) boleto1++;
        if (txtCinco.getText().equals("34")) boleto1++;
        if (txtSeis.getText().equals("34")) boleto1++;
        if (txtAdicional.getText().equals("34")) boleto1++;
        resultadoBoleto1.setText(String.valueOf(boleto1));
    }
    private void boleto2(){
         int boleto2=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("2")) boleto2++;
        if (txtDos.getText().equals("2")) boleto2++;
        if (txtTres.getText().equals("2")) boleto2++;
        if (txtCuatro.getText().equals("2")) boleto2++;
        if (txtCinco.getText().equals("2")) boleto2++;
        if (txtSeis.getText().equals("2")) boleto2++;
        if (txtAdicional.getText().equals("2")) boleto2++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("17")) boleto2++;
        if (txtDos.getText().equals("17")) boleto2++;
        if (txtTres.getText().equals("17")) boleto2++;
        if (txtCuatro.getText().equals("17")) boleto2++;
        if (txtCinco.getText().equals("17")) boleto2++;
        if (txtSeis.getText().equals("17")) boleto2++;
        if (txtAdicional.getText().equals("17")) boleto2++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("51")) boleto2++;
        if (txtDos.getText().equals("51")) boleto2++;
        if (txtTres.getText().equals("51")) boleto2++;
        if (txtCuatro.getText().equals("51")) boleto2++;
        if (txtCinco.getText().equals("51")) boleto2++;
        if (txtSeis.getText().equals("51")) boleto2++;
        if (txtAdicional.getText().equals("51")) boleto2++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("40")) boleto2++;
        if (txtDos.getText().equals("40")) boleto2++;
        if (txtTres.getText().equals("40")) boleto2++;
        if (txtCuatro.getText().equals("40")) boleto2++;
        if (txtCinco.getText().equals("40")) boleto2++;
        if (txtSeis.getText().equals("40")) boleto2++;
        if (txtAdicional.getText().equals("40")) boleto2++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("41")) boleto2++;
        if (txtDos.getText().equals("41")) boleto2++;
        if (txtTres.getText().equals("41")) boleto2++;
        if (txtCuatro.getText().equals("41")) boleto2++;
        if (txtCinco.getText().equals("41")) boleto2++;
        if (txtSeis.getText().equals("41")) boleto2++;
        if (txtAdicional.getText().equals("41")) boleto2++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("16")) boleto2++;
        if (txtDos.getText().equals("16")) boleto2++;
        if (txtTres.getText().equals("16")) boleto2++;
        if (txtCuatro.getText().equals("16")) boleto2++;
        if (txtCinco.getText().equals("16")) boleto2++;
        if (txtSeis.getText().equals("16")) boleto2++;
        if (txtAdicional.getText().equals("16")) boleto2++;
        resultadoBoleto2.setText(String.valueOf(boleto2));
    }
    private void boleto3(){
         int boleto3=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("54")) boleto3++;
        if (txtDos.getText().equals("54")) boleto3++;
        if (txtTres.getText().equals("54")) boleto3++;
        if (txtCuatro.getText().equals("54")) boleto3++;
        if (txtCinco.getText().equals("54")) boleto3++;
        if (txtSeis.getText().equals("54")) boleto3++;
        if (txtAdicional.getText().equals("54")) boleto3++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("32")) boleto3++;
        if (txtDos.getText().equals("32")) boleto3++;
        if (txtTres.getText().equals("32")) boleto3++;
        if (txtCuatro.getText().equals("32")) boleto3++;
        if (txtCinco.getText().equals("32")) boleto3++;
        if (txtSeis.getText().equals("32")) boleto3++;
        if (txtAdicional.getText().equals("32")) boleto3++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("4")) boleto3++;
        if (txtDos.getText().equals("4")) boleto3++;
        if (txtTres.getText().equals("4")) boleto3++;
        if (txtCuatro.getText().equals("4")) boleto3++;
        if (txtCinco.getText().equals("4")) boleto3++;
        if (txtSeis.getText().equals("4")) boleto3++;
        if (txtAdicional.getText().equals("4")) boleto3++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("19")) boleto3++;
        if (txtDos.getText().equals("19")) boleto3++;
        if (txtTres.getText().equals("19")) boleto3++;
        if (txtCuatro.getText().equals("19")) boleto3++;
        if (txtCinco.getText().equals("19")) boleto3++;
        if (txtSeis.getText().equals("19")) boleto3++;
        if (txtAdicional.getText().equals("19")) boleto3++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("7")) boleto3++;
        if (txtDos.getText().equals("7")) boleto3++;
        if (txtTres.getText().equals("7")) boleto3++;
        if (txtCuatro.getText().equals("7")) boleto3++;
        if (txtCinco.getText().equals("7")) boleto3++;
        if (txtSeis.getText().equals("7")) boleto3++;
        if (txtAdicional.getText().equals("7")) boleto3++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("8")) boleto3++;
        if (txtDos.getText().equals("8")) boleto3++;
        if (txtTres.getText().equals("8")) boleto3++;
        if (txtCuatro.getText().equals("8")) boleto3++;
        if (txtCinco.getText().equals("8")) boleto3++;
        if (txtSeis.getText().equals("8")) boleto3++;
        if (txtAdicional.getText().equals("8")) boleto3++;
        resultadoBoleto3.setText(String.valueOf(boleto3));
    }
    private void boleto4(){
         int boleto4=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("43")) boleto4++;
        if (txtDos.getText().equals("43")) boleto4++;
        if (txtTres.getText().equals("43")) boleto4++;
        if (txtCuatro.getText().equals("43")) boleto4++;
        if (txtCinco.getText().equals("43")) boleto4++;
        if (txtSeis.getText().equals("43")) boleto4++;
        if (txtAdicional.getText().equals("43")) boleto4++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("56")) boleto4++;
        if (txtDos.getText().equals("56")) boleto4++;
        if (txtTres.getText().equals("56")) boleto4++;
        if (txtCuatro.getText().equals("56")) boleto4++;
        if (txtCinco.getText().equals("56")) boleto4++;
        if (txtSeis.getText().equals("56")) boleto4++;
        if (txtAdicional.getText().equals("56")) boleto4++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("28")) boleto4++;
        if (txtDos.getText().equals("28")) boleto4++;
        if (txtTres.getText().equals("28")) boleto4++;
        if (txtCuatro.getText().equals("28")) boleto4++;
        if (txtCinco.getText().equals("28")) boleto4++;
        if (txtSeis.getText().equals("28")) boleto4++;
        if (txtAdicional.getText().equals("28")) boleto4++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("18")) boleto4++;
        if (txtDos.getText().equals("18")) boleto4++;
        if (txtTres.getText().equals("18")) boleto4++;
        if (txtCuatro.getText().equals("18")) boleto4++;
        if (txtCinco.getText().equals("18")) boleto4++;
        if (txtSeis.getText().equals("18")) boleto4++;
        if (txtAdicional.getText().equals("18")) boleto4++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("20")) boleto4++;
        if (txtDos.getText().equals("20")) boleto4++;
        if (txtTres.getText().equals("20")) boleto4++;
        if (txtCuatro.getText().equals("20")) boleto4++;
        if (txtCinco.getText().equals("20")) boleto4++;
        if (txtSeis.getText().equals("20")) boleto4++;
        if (txtAdicional.getText().equals("20")) boleto4++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("11")) boleto4++;
        if (txtDos.getText().equals("11")) boleto4++;
        if (txtTres.getText().equals("11")) boleto4++;
        if (txtCuatro.getText().equals("11")) boleto4++;
        if (txtCinco.getText().equals("11")) boleto4++;
        if (txtSeis.getText().equals("11")) boleto4++;
        if (txtAdicional.getText().equals("11")) boleto4++;
        resultadoBoleto4.setText(String.valueOf(boleto4));
    }
    private void boleto5(){
         int boleto5=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("15")) boleto5++;
        if (txtDos.getText().equals("15")) boleto5++;
        if (txtTres.getText().equals("15")) boleto5++;
        if (txtCuatro.getText().equals("15")) boleto5++;
        if (txtCinco.getText().equals("15")) boleto5++;
        if (txtSeis.getText().equals("15")) boleto5++;
        if (txtAdicional.getText().equals("15")) boleto5++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("18")) boleto5++;
        if (txtDos.getText().equals("18")) boleto5++;
        if (txtTres.getText().equals("18")) boleto5++;
        if (txtCuatro.getText().equals("18")) boleto5++;
        if (txtCinco.getText().equals("18")) boleto5++;
        if (txtSeis.getText().equals("18")) boleto5++;
        if (txtAdicional.getText().equals("18")) boleto5++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("40")) boleto5++;
        if (txtDos.getText().equals("40")) boleto5++;
        if (txtTres.getText().equals("40")) boleto5++;
        if (txtCuatro.getText().equals("40")) boleto5++;
        if (txtCinco.getText().equals("40")) boleto5++;
        if (txtSeis.getText().equals("40")) boleto5++;
        if (txtAdicional.getText().equals("40")) boleto5++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("38")) boleto5++;
        if (txtDos.getText().equals("38")) boleto5++;
        if (txtTres.getText().equals("38")) boleto5++;
        if (txtCuatro.getText().equals("38")) boleto5++;
        if (txtCinco.getText().equals("38")) boleto5++;
        if (txtSeis.getText().equals("38")) boleto5++;
        if (txtAdicional.getText().equals("38")) boleto5++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("45")) boleto5++;
        if (txtDos.getText().equals("45")) boleto5++;
        if (txtTres.getText().equals("45")) boleto5++;
        if (txtCuatro.getText().equals("45")) boleto5++;
        if (txtCinco.getText().equals("45")) boleto5++;
        if (txtSeis.getText().equals("45")) boleto5++;
        if (txtAdicional.getText().equals("45")) boleto5++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("55")) boleto5++;
        if (txtDos.getText().equals("55")) boleto5++;
        if (txtTres.getText().equals("55")) boleto5++;
        if (txtCuatro.getText().equals("55")) boleto5++;
        if (txtCinco.getText().equals("55")) boleto5++;
        if (txtSeis.getText().equals("55")) boleto5++;
        if (txtAdicional.getText().equals("55")) boleto5++;
        resultadoBoleto5.setText(String.valueOf(boleto5));
    }
    private void boleto6(){
        int boleto6=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("12")) boleto6++;
        if (txtDos.getText().equals("12")) boleto6++;
        if (txtTres.getText().equals("12")) boleto6++;
        if (txtCuatro.getText().equals("12")) boleto6++;
        if (txtCinco.getText().equals("12")) boleto6++;
        if (txtSeis.getText().equals("12")) boleto6++;
        if (txtAdicional.getText().equals("12")) boleto6++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("40")) boleto6++;
        if (txtDos.getText().equals("40")) boleto6++;
        if (txtTres.getText().equals("40")) boleto6++;
        if (txtCuatro.getText().equals("40")) boleto6++;
        if (txtCinco.getText().equals("40")) boleto6++;
        if (txtSeis.getText().equals("40")) boleto6++;
        if (txtAdicional.getText().equals("40")) boleto6++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("36")) boleto6++;
        if (txtDos.getText().equals("36")) boleto6++;
        if (txtTres.getText().equals("36")) boleto6++;
        if (txtCuatro.getText().equals("36")) boleto6++;
        if (txtCinco.getText().equals("36")) boleto6++;
        if (txtSeis.getText().equals("36")) boleto6++;
        if (txtAdicional.getText().equals("36")) boleto6++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("46")) boleto6++;
        if (txtDos.getText().equals("46")) boleto6++;
        if (txtTres.getText().equals("46")) boleto6++;
        if (txtCuatro.getText().equals("46")) boleto6++;
        if (txtCinco.getText().equals("46")) boleto6++;
        if (txtSeis.getText().equals("46")) boleto6++;
        if (txtAdicional.getText().equals("46")) boleto6++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("44")) boleto6++;
        if (txtDos.getText().equals("44")) boleto6++;
        if (txtTres.getText().equals("44")) boleto6++;
        if (txtCuatro.getText().equals("44")) boleto6++;
        if (txtCinco.getText().equals("44")) boleto6++;
        if (txtSeis.getText().equals("44")) boleto6++;
        if (txtAdicional.getText().equals("44")) boleto6++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("13")) boleto6++;
        if (txtDos.getText().equals("13")) boleto6++;
        if (txtTres.getText().equals("13")) boleto6++;
        if (txtCuatro.getText().equals("13")) boleto6++;
        if (txtCinco.getText().equals("13")) boleto6++;
        if (txtSeis.getText().equals("13")) boleto6++;
        if (txtAdicional.getText().equals("13")) boleto6++;
        resultadoBoleto6.setText(String.valueOf(boleto6));
    }
    private void boleto7(){
        int boleto7=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("32")) boleto7++;
        if (txtDos.getText().equals("32")) boleto7++;
        if (txtTres.getText().equals("32")) boleto7++;
        if (txtCuatro.getText().equals("32")) boleto7++;
        if (txtCinco.getText().equals("32")) boleto7++;
        if (txtSeis.getText().equals("32")) boleto7++;
        if (txtAdicional.getText().equals("32")) boleto7++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("44")) boleto7++;
        if (txtDos.getText().equals("44")) boleto7++;
        if (txtTres.getText().equals("44")) boleto7++;
        if (txtCuatro.getText().equals("44")) boleto7++;
        if (txtCinco.getText().equals("44")) boleto7++;
        if (txtSeis.getText().equals("44")) boleto7++;
        if (txtAdicional.getText().equals("44")) boleto7++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("13")) boleto7++;
        if (txtDos.getText().equals("13")) boleto7++;
        if (txtTres.getText().equals("13")) boleto7++;
        if (txtCuatro.getText().equals("13")) boleto7++;
        if (txtCinco.getText().equals("13")) boleto7++;
        if (txtSeis.getText().equals("13")) boleto7++;
        if (txtAdicional.getText().equals("13")) boleto7++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("10")) boleto7++;
        if (txtDos.getText().equals("10")) boleto7++;
        if (txtTres.getText().equals("10")) boleto7++;
        if (txtCuatro.getText().equals("10")) boleto7++;
        if (txtCinco.getText().equals("10")) boleto7++;
        if (txtSeis.getText().equals("10")) boleto7++;
        if (txtAdicional.getText().equals("10")) boleto7++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("18")) boleto7++;
        if (txtDos.getText().equals("18")) boleto7++;
        if (txtTres.getText().equals("18")) boleto7++;
        if (txtCuatro.getText().equals("18")) boleto7++;
        if (txtCinco.getText().equals("18")) boleto7++;
        if (txtSeis.getText().equals("18")) boleto7++;
        if (txtAdicional.getText().equals("18")) boleto7++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("31")) boleto7++;
        if (txtDos.getText().equals("31")) boleto7++;
        if (txtTres.getText().equals("31")) boleto7++;
        if (txtCuatro.getText().equals("31")) boleto7++;
        if (txtCinco.getText().equals("31")) boleto7++;
        if (txtSeis.getText().equals("31")) boleto7++;
        if (txtAdicional.getText().equals("31")) boleto7++;
        resultadoBoleto7.setText(String.valueOf(boleto7));
    }
    private void boleto8(){
        int boleto8=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("8")) boleto8++;
        if (txtDos.getText().equals("8")) boleto8++;
        if (txtTres.getText().equals("8")) boleto8++;
        if (txtCuatro.getText().equals("8")) boleto8++;
        if (txtCinco.getText().equals("8")) boleto8++;
        if (txtSeis.getText().equals("8")) boleto8++;
        if (txtAdicional.getText().equals("8")) boleto8++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("33")) boleto8++;
        if (txtDos.getText().equals("33")) boleto8++;
        if (txtTres.getText().equals("33")) boleto8++;
        if (txtCuatro.getText().equals("33")) boleto8++;
        if (txtCinco.getText().equals("33")) boleto8++;
        if (txtSeis.getText().equals("33")) boleto8++;
        if (txtAdicional.getText().equals("33")) boleto8++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("30")) boleto8++;
        if (txtDos.getText().equals("30")) boleto8++;
        if (txtTres.getText().equals("30")) boleto8++;
        if (txtCuatro.getText().equals("30")) boleto8++;
        if (txtCinco.getText().equals("30")) boleto8++;
        if (txtSeis.getText().equals("30")) boleto8++;
        if (txtAdicional.getText().equals("30")) boleto8++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("31")) boleto8++;
        if (txtDos.getText().equals("31")) boleto8++;
        if (txtTres.getText().equals("31")) boleto8++;
        if (txtCuatro.getText().equals("31")) boleto8++;
        if (txtCinco.getText().equals("31")) boleto8++;
        if (txtSeis.getText().equals("31")) boleto8++;
        if (txtAdicional.getText().equals("31")) boleto8++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("47")) boleto8++;
        if (txtDos.getText().equals("47")) boleto8++;
        if (txtTres.getText().equals("47")) boleto8++;
        if (txtCuatro.getText().equals("47")) boleto8++;
        if (txtCinco.getText().equals("47")) boleto8++;
        if (txtSeis.getText().equals("47")) boleto8++;
        if (txtAdicional.getText().equals("47")) boleto8++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("43")) boleto8++;
        if (txtDos.getText().equals("43")) boleto8++;
        if (txtTres.getText().equals("43")) boleto8++;
        if (txtCuatro.getText().equals("43")) boleto8++;
        if (txtCinco.getText().equals("43")) boleto8++;
        if (txtSeis.getText().equals("43")) boleto8++;
        if (txtAdicional.getText().equals("43")) boleto8++;
        resultadoBoleto8.setText(String.valueOf(boleto8));
    }
    private void boleto9(){
         int boleto9=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("14")) boleto9++;
        if (txtDos.getText().equals("14")) boleto9++;
        if (txtTres.getText().equals("14")) boleto9++;
        if (txtCuatro.getText().equals("14")) boleto9++;
        if (txtCinco.getText().equals("14")) boleto9++;
        if (txtSeis.getText().equals("14")) boleto9++;
        if (txtAdicional.getText().equals("14")) boleto9++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("27")) boleto9++;
        if (txtDos.getText().equals("27")) boleto9++;
        if (txtTres.getText().equals("27")) boleto9++;
        if (txtCuatro.getText().equals("27")) boleto9++;
        if (txtCinco.getText().equals("27")) boleto9++;
        if (txtSeis.getText().equals("27")) boleto9++;
        if (txtAdicional.getText().equals("27")) boleto9++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("12")) boleto9++;
        if (txtDos.getText().equals("12")) boleto9++;
        if (txtTres.getText().equals("12")) boleto9++;
        if (txtCuatro.getText().equals("12")) boleto9++;
        if (txtCinco.getText().equals("12")) boleto9++;
        if (txtSeis.getText().equals("12")) boleto9++;
        if (txtAdicional.getText().equals("12")) boleto9++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("39")) boleto9++;
        if (txtDos.getText().equals("39")) boleto9++;
        if (txtTres.getText().equals("39")) boleto9++;
        if (txtCuatro.getText().equals("39")) boleto9++;
        if (txtCinco.getText().equals("39")) boleto9++;
        if (txtSeis.getText().equals("39")) boleto9++;
        if (txtAdicional.getText().equals("39")) boleto9++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("41")) boleto9++;
        if (txtDos.getText().equals("41")) boleto9++;
        if (txtTres.getText().equals("41")) boleto9++;
        if (txtCuatro.getText().equals("41")) boleto9++;
        if (txtCinco.getText().equals("41")) boleto9++;
        if (txtSeis.getText().equals("41")) boleto9++;
        if (txtAdicional.getText().equals("41")) boleto9++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("35")) boleto9++;
        if (txtDos.getText().equals("35")) boleto9++;
        if (txtTres.getText().equals("35")) boleto9++;
        if (txtCuatro.getText().equals("35")) boleto9++;
        if (txtCinco.getText().equals("35")) boleto9++;
        if (txtSeis.getText().equals("35")) boleto9++;
        if (txtAdicional.getText().equals("35")) boleto9++;
        resultadoBoleto9.setText(String.valueOf(boleto9));
    }
    private void boleto10(){
         int boleto10=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("46")) boleto10++;
        if (txtDos.getText().equals("46")) boleto10++;
        if (txtTres.getText().equals("46")) boleto10++;
        if (txtCuatro.getText().equals("46")) boleto10++;
        if (txtCinco.getText().equals("46")) boleto10++;
        if (txtSeis.getText().equals("46")) boleto10++;
        if (txtAdicional.getText().equals("46")) boleto10++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("49")) boleto10++;
        if (txtDos.getText().equals("49")) boleto10++;
        if (txtTres.getText().equals("49")) boleto10++;
        if (txtCuatro.getText().equals("49")) boleto10++;
        if (txtCinco.getText().equals("49")) boleto10++;
        if (txtSeis.getText().equals("49")) boleto10++;
        if (txtAdicional.getText().equals("49")) boleto10++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("35")) boleto10++;
        if (txtDos.getText().equals("35")) boleto10++;
        if (txtTres.getText().equals("35")) boleto10++;
        if (txtCuatro.getText().equals("35")) boleto10++;
        if (txtCinco.getText().equals("35")) boleto10++;
        if (txtSeis.getText().equals("35")) boleto10++;
        if (txtAdicional.getText().equals("35")) boleto10++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("43")) boleto10++;
        if (txtDos.getText().equals("43")) boleto10++;
        if (txtTres.getText().equals("43")) boleto10++;
        if (txtCuatro.getText().equals("43")) boleto10++;
        if (txtCinco.getText().equals("43")) boleto10++;
        if (txtSeis.getText().equals("43")) boleto10++;
        if (txtAdicional.getText().equals("43")) boleto10++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("6")) boleto10++;
        if (txtDos.getText().equals("6")) boleto10++;
        if (txtTres.getText().equals("6")) boleto10++;
        if (txtCuatro.getText().equals("6")) boleto10++;
        if (txtCinco.getText().equals("6")) boleto10++;
        if (txtSeis.getText().equals("6")) boleto10++;
        if (txtAdicional.getText().equals("6")) boleto10++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("48")) boleto10++;
        if (txtDos.getText().equals("48")) boleto10++;
        if (txtTres.getText().equals("48")) boleto10++;
        if (txtCuatro.getText().equals("48")) boleto10++;
        if (txtCinco.getText().equals("48")) boleto10++;
        if (txtSeis.getText().equals("48")) boleto10++;
        if (txtAdicional.getText().equals("48")) boleto10++;
        resultadoBoleto10.setText(String.valueOf(boleto10));
    }
    
    private void boleto11(){
        int boleto11=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("45")) boleto11++;
        if (txtDos.getText().equals("45")) boleto11++;
        if (txtTres.getText().equals("45")) boleto11++;
        if (txtCuatro.getText().equals("45")) boleto11++;
        if (txtCinco.getText().equals("45")) boleto11++;
        if (txtSeis.getText().equals("45")) boleto11++;
        if (txtAdicional.getText().equals("45")) boleto11++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("7")) boleto11++;
        if (txtDos.getText().equals("7")) boleto11++;
        if (txtTres.getText().equals("7")) boleto11++;
        if (txtCuatro.getText().equals("7")) boleto11++;
        if (txtCinco.getText().equals("7")) boleto11++;
        if (txtSeis.getText().equals("7")) boleto11++;
        if (txtAdicional.getText().equals("7")) boleto11++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("36")) boleto11++;
        if (txtDos.getText().equals("36")) boleto11++;
        if (txtTres.getText().equals("36")) boleto11++;
        if (txtCuatro.getText().equals("36")) boleto11++;
        if (txtCinco.getText().equals("36")) boleto11++;
        if (txtSeis.getText().equals("36")) boleto11++;
        if (txtAdicional.getText().equals("36")) boleto11++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("30")) boleto11++;
        if (txtDos.getText().equals("30")) boleto11++;
        if (txtTres.getText().equals("30")) boleto11++;
        if (txtCuatro.getText().equals("30")) boleto11++;
        if (txtCinco.getText().equals("30")) boleto11++;
        if (txtSeis.getText().equals("30")) boleto11++;
        if (txtAdicional.getText().equals("30")) boleto11++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("22")) boleto11++;
        if (txtDos.getText().equals("22")) boleto11++;
        if (txtTres.getText().equals("22")) boleto11++;
        if (txtCuatro.getText().equals("22")) boleto11++;
        if (txtCinco.getText().equals("22")) boleto11++;
        if (txtSeis.getText().equals("22")) boleto11++;
        if (txtAdicional.getText().equals("22")) boleto11++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("19")) boleto11++;
        if (txtDos.getText().equals("19")) boleto11++;
        if (txtTres.getText().equals("19")) boleto11++;
        if (txtCuatro.getText().equals("19")) boleto11++;
        if (txtCinco.getText().equals("19")) boleto11++;
        if (txtSeis.getText().equals("19")) boleto11++;
        if (txtAdicional.getText().equals("19")) boleto11++;
        resultadoBoleto11.setText(String.valueOf(boleto11));
    }
    private void boleto12(){
         int boleto12=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("20")) boleto12++;
        if (txtDos.getText().equals("20")) boleto12++;
        if (txtTres.getText().equals("20")) boleto12++;
        if (txtCuatro.getText().equals("20")) boleto12++;
        if (txtCinco.getText().equals("20")) boleto12++;
        if (txtSeis.getText().equals("20")) boleto12++;
        if (txtAdicional.getText().equals("20")) boleto12++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("39")) boleto12++;
        if (txtDos.getText().equals("39")) boleto12++;
        if (txtTres.getText().equals("39")) boleto12++;
        if (txtCuatro.getText().equals("39")) boleto12++;
        if (txtCinco.getText().equals("39")) boleto12++;
        if (txtSeis.getText().equals("39")) boleto12++;
        if (txtAdicional.getText().equals("39")) boleto12++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("29")) boleto12++;
        if (txtDos.getText().equals("29")) boleto12++;
        if (txtTres.getText().equals("29")) boleto12++;
        if (txtCuatro.getText().equals("29")) boleto12++;
        if (txtCinco.getText().equals("29")) boleto12++;
        if (txtSeis.getText().equals("29")) boleto12++;
        if (txtAdicional.getText().equals("29")) boleto12++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("10")) boleto12++;
        if (txtDos.getText().equals("10")) boleto12++;
        if (txtTres.getText().equals("10")) boleto12++;
        if (txtCuatro.getText().equals("10")) boleto12++;
        if (txtCinco.getText().equals("10")) boleto12++;
        if (txtSeis.getText().equals("10")) boleto12++;
        if (txtAdicional.getText().equals("10")) boleto12++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("22")) boleto12++;
        if (txtDos.getText().equals("22")) boleto12++;
        if (txtTres.getText().equals("22")) boleto12++;
        if (txtCuatro.getText().equals("22")) boleto12++;
        if (txtCinco.getText().equals("22")) boleto12++;
        if (txtSeis.getText().equals("22")) boleto12++;
        if (txtAdicional.getText().equals("22")) boleto12++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("19")) boleto12++;
        if (txtDos.getText().equals("19")) boleto12++;
        if (txtTres.getText().equals("19")) boleto12++;
        if (txtCuatro.getText().equals("19")) boleto12++;
        if (txtCinco.getText().equals("19")) boleto12++;
        if (txtSeis.getText().equals("19")) boleto12++;
        if (txtAdicional.getText().equals("19")) boleto12++;
        resultadoBoleto12.setText(String.valueOf(boleto12));
    }
    private void boleto13(){
         int boleto13=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("53")) boleto13++;
        if (txtDos.getText().equals("53")) boleto13++;
        if (txtTres.getText().equals("53")) boleto13++;
        if (txtCuatro.getText().equals("53")) boleto13++;
        if (txtCinco.getText().equals("53")) boleto13++;
        if (txtSeis.getText().equals("53")) boleto13++;
        if (txtAdicional.getText().equals("53")) boleto13++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("8")) boleto13++;
        if (txtDos.getText().equals("8")) boleto13++;
        if (txtTres.getText().equals("8")) boleto13++;
        if (txtCuatro.getText().equals("8")) boleto13++;
        if (txtCinco.getText().equals("8")) boleto13++;
        if (txtSeis.getText().equals("8")) boleto13++;
        if (txtAdicional.getText().equals("8")) boleto13++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("47")) boleto13++;
        if (txtDos.getText().equals("47")) boleto13++;
        if (txtTres.getText().equals("47")) boleto13++;
        if (txtCuatro.getText().equals("47")) boleto13++;
        if (txtCinco.getText().equals("47")) boleto13++;
        if (txtSeis.getText().equals("47")) boleto13++;
        if (txtAdicional.getText().equals("47")) boleto13++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("30")) boleto13++;
        if (txtDos.getText().equals("30")) boleto13++;
        if (txtTres.getText().equals("30")) boleto13++;
        if (txtCuatro.getText().equals("30")) boleto13++;
        if (txtCinco.getText().equals("30")) boleto13++;
        if (txtSeis.getText().equals("30")) boleto13++;
        if (txtAdicional.getText().equals("30")) boleto13++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("12")) boleto13++;
        if (txtDos.getText().equals("12")) boleto13++;
        if (txtTres.getText().equals("12")) boleto13++;
        if (txtCuatro.getText().equals("12")) boleto13++;
        if (txtCinco.getText().equals("12")) boleto13++;
        if (txtSeis.getText().equals("12")) boleto13++;
        if (txtAdicional.getText().equals("12")) boleto13++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("13")) boleto13++;
        if (txtDos.getText().equals("13")) boleto13++;
        if (txtTres.getText().equals("13")) boleto13++;
        if (txtCuatro.getText().equals("13")) boleto13++;
        if (txtCinco.getText().equals("13")) boleto13++;
        if (txtSeis.getText().equals("13")) boleto13++;
        if (txtAdicional.getText().equals("13")) boleto13++;
        resultadoBoleto13.setText(String.valueOf(boleto13));
    }
    private void boleto14(){
         int boleto14=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("17")) boleto14++;
        if (txtDos.getText().equals("17")) boleto14++;
        if (txtTres.getText().equals("17")) boleto14++;
        if (txtCuatro.getText().equals("17")) boleto14++;
        if (txtCinco.getText().equals("17")) boleto14++;
        if (txtSeis.getText().equals("17")) boleto14++;
        if (txtAdicional.getText().equals("17")) boleto14++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("13")) boleto14++;
        if (txtDos.getText().equals("13")) boleto14++;
        if (txtTres.getText().equals("13")) boleto14++;
        if (txtCuatro.getText().equals("13")) boleto14++;
        if (txtCinco.getText().equals("13")) boleto14++;
        if (txtSeis.getText().equals("13")) boleto14++;
        if (txtAdicional.getText().equals("13")) boleto14++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("2")) boleto14++;
        if (txtDos.getText().equals("2")) boleto14++;
        if (txtTres.getText().equals("2")) boleto14++;
        if (txtCuatro.getText().equals("2")) boleto14++;
        if (txtCinco.getText().equals("2")) boleto14++;
        if (txtSeis.getText().equals("2")) boleto14++;
        if (txtAdicional.getText().equals("2")) boleto14++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("5")) boleto14++;
        if (txtDos.getText().equals("5")) boleto14++;
        if (txtTres.getText().equals("5")) boleto14++;
        if (txtCuatro.getText().equals("5")) boleto14++;
        if (txtCinco.getText().equals("5")) boleto14++;
        if (txtSeis.getText().equals("5")) boleto14++;
        if (txtAdicional.getText().equals("5")) boleto14++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("27")) boleto14++;
        if (txtDos.getText().equals("27")) boleto14++;
        if (txtTres.getText().equals("27")) boleto14++;
        if (txtCuatro.getText().equals("27")) boleto14++;
        if (txtCinco.getText().equals("27")) boleto14++;
        if (txtSeis.getText().equals("27")) boleto14++;
        if (txtAdicional.getText().equals("27")) boleto14++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("6")) boleto14++;
        if (txtDos.getText().equals("6")) boleto14++;
        if (txtTres.getText().equals("6")) boleto14++;
        if (txtCuatro.getText().equals("6")) boleto14++;
        if (txtCinco.getText().equals("6")) boleto14++;
        if (txtSeis.getText().equals("6")) boleto14++;
        if (txtAdicional.getText().equals("6")) boleto14++;
        resultadoBoleto14.setText(String.valueOf(boleto14));
    }
    private void boleto15(){
         int boleto15=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("24")) boleto15++;
        if (txtDos.getText().equals("24")) boleto15++;
        if (txtTres.getText().equals("24")) boleto15++;
        if (txtCuatro.getText().equals("24")) boleto15++;
        if (txtCinco.getText().equals("24")) boleto15++;
        if (txtSeis.getText().equals("24")) boleto15++;
        if (txtAdicional.getText().equals("24")) boleto15++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("39")) boleto15++;
        if (txtDos.getText().equals("39")) boleto15++;
        if (txtTres.getText().equals("39")) boleto15++;
        if (txtCuatro.getText().equals("39")) boleto15++;
        if (txtCinco.getText().equals("39")) boleto15++;
        if (txtSeis.getText().equals("39")) boleto15++;
        if (txtAdicional.getText().equals("39")) boleto15++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("13")) boleto15++;
        if (txtDos.getText().equals("13")) boleto15++;
        if (txtTres.getText().equals("13")) boleto15++;
        if (txtCuatro.getText().equals("13")) boleto15++;
        if (txtCinco.getText().equals("13")) boleto15++;
        if (txtSeis.getText().equals("13")) boleto15++;
        if (txtAdicional.getText().equals("13")) boleto15++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("20")) boleto15++;
        if (txtDos.getText().equals("20")) boleto15++;
        if (txtTres.getText().equals("20")) boleto15++;
        if (txtCuatro.getText().equals("20")) boleto15++;
        if (txtCinco.getText().equals("20")) boleto15++;
        if (txtSeis.getText().equals("20")) boleto15++;
        if (txtAdicional.getText().equals("20")) boleto15++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("22")) boleto15++;
        if (txtDos.getText().equals("22")) boleto15++;
        if (txtTres.getText().equals("22")) boleto15++;
        if (txtCuatro.getText().equals("22")) boleto15++;
        if (txtCinco.getText().equals("22")) boleto15++;
        if (txtSeis.getText().equals("22")) boleto15++;
        if (txtAdicional.getText().equals("22")) boleto15++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("10")) boleto15++;
        if (txtDos.getText().equals("10")) boleto15++;
        if (txtTres.getText().equals("10")) boleto15++;
        if (txtCuatro.getText().equals("10")) boleto15++;
        if (txtCinco.getText().equals("10")) boleto15++;
        if (txtSeis.getText().equals("10")) boleto15++;
        if (txtAdicional.getText().equals("10")) boleto15++;
        resultadoBoleto15.setText(String.valueOf(boleto15));
    }
    private void boleto16(){
        int boleto16=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("41")) boleto16++;
        if (txtDos.getText().equals("41")) boleto16++;
        if (txtTres.getText().equals("41")) boleto16++;
        if (txtCuatro.getText().equals("41")) boleto16++;
        if (txtCinco.getText().equals("41")) boleto16++;
        if (txtSeis.getText().equals("41")) boleto16++;
        if (txtAdicional.getText().equals("41")) boleto16++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("7")) boleto16++;
        if (txtDos.getText().equals("7")) boleto16++;
        if (txtTres.getText().equals("7")) boleto16++;
        if (txtCuatro.getText().equals("7")) boleto16++;
        if (txtCinco.getText().equals("7")) boleto16++;
        if (txtSeis.getText().equals("7")) boleto16++;
        if (txtAdicional.getText().equals("7")) boleto16++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("33")) boleto16++;
        if (txtDos.getText().equals("33")) boleto16++;
        if (txtTres.getText().equals("33")) boleto16++;
        if (txtCuatro.getText().equals("33")) boleto16++;
        if (txtCinco.getText().equals("33")) boleto16++;
        if (txtSeis.getText().equals("33")) boleto16++;
        if (txtAdicional.getText().equals("33")) boleto16++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("38")) boleto16++;
        if (txtDos.getText().equals("38")) boleto16++;
        if (txtTres.getText().equals("38")) boleto16++;
        if (txtCuatro.getText().equals("38")) boleto16++;
        if (txtCinco.getText().equals("38")) boleto16++;
        if (txtSeis.getText().equals("38")) boleto16++;
        if (txtAdicional.getText().equals("38")) boleto16++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("3")) boleto16++;
        if (txtDos.getText().equals("3")) boleto16++;
        if (txtTres.getText().equals("3")) boleto16++;
        if (txtCuatro.getText().equals("3")) boleto16++;
        if (txtCinco.getText().equals("3")) boleto16++;
        if (txtSeis.getText().equals("3")) boleto16++;
        if (txtAdicional.getText().equals("3")) boleto16++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("13")) boleto16++;
        if (txtDos.getText().equals("13")) boleto16++;
        if (txtTres.getText().equals("13")) boleto16++;
        if (txtCuatro.getText().equals("13")) boleto16++;
        if (txtCinco.getText().equals("13")) boleto16++;
        if (txtSeis.getText().equals("13")) boleto16++;
        if (txtAdicional.getText().equals("13")) boleto16++;
        resultadoBoleto16.setText(String.valueOf(boleto16));
    }
    private void boleto17(){
        int boleto17=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("19")) boleto17++;
        if (txtDos.getText().equals("19")) boleto17++;
        if (txtTres.getText().equals("19")) boleto17++;
        if (txtCuatro.getText().equals("19")) boleto17++;
        if (txtCinco.getText().equals("19")) boleto17++;
        if (txtSeis.getText().equals("19")) boleto17++;
        if (txtAdicional.getText().equals("19")) boleto17++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("38")) boleto17++;
        if (txtDos.getText().equals("38")) boleto17++;
        if (txtTres.getText().equals("38")) boleto17++;
        if (txtCuatro.getText().equals("38")) boleto17++;
        if (txtCinco.getText().equals("38")) boleto17++;
        if (txtSeis.getText().equals("38")) boleto17++;
        if (txtAdicional.getText().equals("38")) boleto17++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("37")) boleto17++;
        if (txtDos.getText().equals("37")) boleto17++;
        if (txtTres.getText().equals("37")) boleto17++;
        if (txtCuatro.getText().equals("37")) boleto17++;
        if (txtCinco.getText().equals("37")) boleto17++;
        if (txtSeis.getText().equals("37")) boleto17++;
        if (txtAdicional.getText().equals("37")) boleto17++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("25")) boleto17++;
        if (txtDos.getText().equals("25")) boleto17++;
        if (txtTres.getText().equals("25")) boleto17++;
        if (txtCuatro.getText().equals("25")) boleto17++;
        if (txtCinco.getText().equals("25")) boleto17++;
        if (txtSeis.getText().equals("25")) boleto17++;
        if (txtAdicional.getText().equals("25")) boleto17++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("51")) boleto17++;
        if (txtDos.getText().equals("51")) boleto17++;
        if (txtTres.getText().equals("51")) boleto17++;
        if (txtCuatro.getText().equals("51")) boleto17++;
        if (txtCinco.getText().equals("51")) boleto17++;
        if (txtSeis.getText().equals("51")) boleto17++;
        if (txtAdicional.getText().equals("51")) boleto17++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("2")) boleto17++;
        if (txtDos.getText().equals("2")) boleto17++;
        if (txtTres.getText().equals("2")) boleto17++;
        if (txtCuatro.getText().equals("2")) boleto17++;
        if (txtCinco.getText().equals("2")) boleto17++;
        if (txtSeis.getText().equals("2")) boleto17++;
        if (txtAdicional.getText().equals("2")) boleto17++;
        resultadoBoleto17.setText(String.valueOf(boleto17));
    }
    private void boleto18(){
        int boleto18=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("54")) boleto18++;
        if (txtDos.getText().equals("54")) boleto18++;
        if (txtTres.getText().equals("54")) boleto18++;
        if (txtCuatro.getText().equals("54")) boleto18++;
        if (txtCinco.getText().equals("54")) boleto18++;
        if (txtSeis.getText().equals("54")) boleto18++;
        if (txtAdicional.getText().equals("54")) boleto18++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("47")) boleto18++;
        if (txtDos.getText().equals("47")) boleto18++;
        if (txtTres.getText().equals("47")) boleto18++;
        if (txtCuatro.getText().equals("47")) boleto18++;
        if (txtCinco.getText().equals("47")) boleto18++;
        if (txtSeis.getText().equals("47")) boleto18++;
        if (txtAdicional.getText().equals("47")) boleto18++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("34")) boleto18++;
        if (txtDos.getText().equals("34")) boleto18++;
        if (txtTres.getText().equals("34")) boleto18++;
        if (txtCuatro.getText().equals("34")) boleto18++;
        if (txtCinco.getText().equals("34")) boleto18++;
        if (txtSeis.getText().equals("34")) boleto18++;
        if (txtAdicional.getText().equals("34")) boleto18++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("35")) boleto18++;
        if (txtDos.getText().equals("35")) boleto18++;
        if (txtTres.getText().equals("35")) boleto18++;
        if (txtCuatro.getText().equals("35")) boleto18++;
        if (txtCinco.getText().equals("35")) boleto18++;
        if (txtSeis.getText().equals("35")) boleto18++;
        if (txtAdicional.getText().equals("35")) boleto18++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("42")) boleto18++;
        if (txtDos.getText().equals("42")) boleto18++;
        if (txtTres.getText().equals("42")) boleto18++;
        if (txtCuatro.getText().equals("42")) boleto18++;
        if (txtCinco.getText().equals("42")) boleto18++;
        if (txtSeis.getText().equals("42")) boleto18++;
        if (txtAdicional.getText().equals("42")) boleto18++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("51")) boleto18++;
        if (txtDos.getText().equals("51")) boleto18++;
        if (txtTres.getText().equals("51")) boleto18++;
        if (txtCuatro.getText().equals("51")) boleto18++;
        if (txtCinco.getText().equals("51")) boleto18++;
        if (txtSeis.getText().equals("51")) boleto18++;
        if (txtAdicional.getText().equals("51")) boleto18++;
        resultadoBoleto18.setText(String.valueOf(boleto18));
    }
    private void boleto19(){
         int boleto19=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("1")) boleto19++;
        if (txtDos.getText().equals("1")) boleto19++;
        if (txtTres.getText().equals("1")) boleto19++;
        if (txtCuatro.getText().equals("1")) boleto19++;
        if (txtCinco.getText().equals("1")) boleto19++;
        if (txtSeis.getText().equals("1")) boleto19++;
        if (txtAdicional.getText().equals("1")) boleto19++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("43")) boleto19++;
        if (txtDos.getText().equals("43")) boleto19++;
        if (txtTres.getText().equals("43")) boleto19++;
        if (txtCuatro.getText().equals("43")) boleto19++;
        if (txtCinco.getText().equals("43")) boleto19++;
        if (txtSeis.getText().equals("43")) boleto19++;
        if (txtAdicional.getText().equals("43")) boleto19++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("46")) boleto19++;
        if (txtDos.getText().equals("46")) boleto19++;
        if (txtTres.getText().equals("46")) boleto19++;
        if (txtCuatro.getText().equals("46")) boleto19++;
        if (txtCinco.getText().equals("46")) boleto19++;
        if (txtSeis.getText().equals("46")) boleto19++;
        if (txtAdicional.getText().equals("46")) boleto19++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("31")) boleto19++;
        if (txtDos.getText().equals("31")) boleto19++;
        if (txtTres.getText().equals("31")) boleto19++;
        if (txtCuatro.getText().equals("31")) boleto19++;
        if (txtCinco.getText().equals("31")) boleto19++;
        if (txtSeis.getText().equals("31")) boleto19++;
        if (txtAdicional.getText().equals("31")) boleto19++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("25")) boleto19++;
        if (txtDos.getText().equals("25")) boleto19++;
        if (txtTres.getText().equals("25")) boleto19++;
        if (txtCuatro.getText().equals("25")) boleto19++;
        if (txtCinco.getText().equals("25")) boleto19++;
        if (txtSeis.getText().equals("25")) boleto19++;
        if (txtAdicional.getText().equals("25")) boleto19++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("24")) boleto19++;
        if (txtDos.getText().equals("24")) boleto19++;
        if (txtTres.getText().equals("24")) boleto19++;
        if (txtCuatro.getText().equals("24")) boleto19++;
        if (txtCinco.getText().equals("24")) boleto19++;
        if (txtSeis.getText().equals("24")) boleto19++;
        if (txtAdicional.getText().equals("24")) boleto19++;
        resultadoBoleto19.setText(String.valueOf(boleto19));
    }
    private void boleto20(){
         int boleto20=0;
        //verificamos el primer numero
        if (txtUno.getText().equals("56")) boleto20++;
        if (txtDos.getText().equals("56")) boleto20++;
        if (txtTres.getText().equals("56")) boleto20++;
        if (txtCuatro.getText().equals("56")) boleto20++;
        if (txtCinco.getText().equals("56")) boleto20++;
        if (txtSeis.getText().equals("56")) boleto20++;
        if (txtAdicional.getText().equals("56")) boleto20++;
        //verificamos el segundo numero numero
        if (txtUno.getText().equals("28")) boleto20++;
        if (txtDos.getText().equals("28")) boleto20++;
        if (txtTres.getText().equals("28")) boleto20++;
        if (txtCuatro.getText().equals("28")) boleto20++;
        if (txtCinco.getText().equals("28")) boleto20++;
        if (txtSeis.getText().equals("28")) boleto20++;
        if (txtAdicional.getText().equals("28")) boleto20++;
        //verificamos el tercero numero numero
        if (txtUno.getText().equals("31")) boleto20++;
        if (txtDos.getText().equals("31")) boleto20++;
        if (txtTres.getText().equals("31")) boleto20++;
        if (txtCuatro.getText().equals("31")) boleto20++;
        if (txtCinco.getText().equals("31")) boleto20++;
        if (txtSeis.getText().equals("31")) boleto20++;
        if (txtAdicional.getText().equals("31")) boleto20++;
        //verificamos el cuarto numero numero
        if (txtUno.getText().equals("54")) boleto20++;
        if (txtDos.getText().equals("54")) boleto20++;
        if (txtTres.getText().equals("54")) boleto20++;
        if (txtCuatro.getText().equals("54")) boleto20++;
        if (txtCinco.getText().equals("54")) boleto20++;
        if (txtSeis.getText().equals("54")) boleto20++;
        if (txtAdicional.getText().equals("54")) boleto20++;
        //verificamos el Quinto numero numero
        if (txtUno.getText().equals("30")) boleto20++;
        if (txtDos.getText().equals("30")) boleto20++;
        if (txtTres.getText().equals("30")) boleto20++;
        if (txtCuatro.getText().equals("30")) boleto20++;
        if (txtCinco.getText().equals("30")) boleto20++;
        if (txtSeis.getText().equals("30")) boleto20++;
        if (txtAdicional.getText().equals("30")) boleto20++;
        //verificamos el Sexto numero numero
        if (txtUno.getText().equals("46")) boleto20++;
        if (txtDos.getText().equals("46")) boleto20++;
        if (txtTres.getText().equals("46")) boleto20++;
        if (txtCuatro.getText().equals("46")) boleto20++;
        if (txtCinco.getText().equals("46")) boleto20++;
        if (txtSeis.getText().equals("46")) boleto20++;
        if (txtAdicional.getText().equals("46")) boleto20++;
        resultadoBoleto10.setText(String.valueOf(boleto20));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuerte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel resultadoBoleto1;
    private javax.swing.JLabel resultadoBoleto10;
    private javax.swing.JLabel resultadoBoleto11;
    private javax.swing.JLabel resultadoBoleto12;
    private javax.swing.JLabel resultadoBoleto13;
    private javax.swing.JLabel resultadoBoleto14;
    private javax.swing.JLabel resultadoBoleto15;
    private javax.swing.JLabel resultadoBoleto16;
    private javax.swing.JLabel resultadoBoleto17;
    private javax.swing.JLabel resultadoBoleto18;
    private javax.swing.JLabel resultadoBoleto19;
    private javax.swing.JLabel resultadoBoleto2;
    private javax.swing.JLabel resultadoBoleto20;
    private javax.swing.JLabel resultadoBoleto3;
    private javax.swing.JLabel resultadoBoleto4;
    private javax.swing.JLabel resultadoBoleto5;
    private javax.swing.JLabel resultadoBoleto6;
    private javax.swing.JLabel resultadoBoleto7;
    private javax.swing.JLabel resultadoBoleto8;
    private javax.swing.JLabel resultadoBoleto9;
    private javax.swing.JTextField txtAdicional;
    private javax.swing.JTextField txtCinco;
    private javax.swing.JTextField txtCuatro;
    private javax.swing.JTextField txtDos;
    private javax.swing.JTextField txtSeis;
    private javax.swing.JTextField txtTres;
    private javax.swing.JTextField txtUno;
    // End of variables declaration//GEN-END:variables
}
